### ISSUE TITLE
The library 'package:loading_overlay/loading_overlay.dart' is legacy, and should not be imported into a null safe library.

### ISSUE THREAD

**Issue by Lakhankumawat** [java-james/loading_overlay#13]
Same was the error using **modal_progress_hud** i used this package hopeful that it would work but it showed this warning .
<br><br><hr>

![Screenshot 2021-06-27 185445](https://user-images.githubusercontent.com/55774240/123546183-30857780-d779-11eb-98bf-ddd755596cca.png)

Please resolve this issue

**Comment by java-james** [comment]
Thanks for opening the issue - This library should have been migrated to null safety in 0.3.0. I will try reproduce. Are you using the latest (3.0.0)
<img width="549" alt="Screen Shot 2021-07-05 at 11 55 58 AM" src="https://user-images.githubusercontent.com/22756998/124403014-f83cf500-dd87-11eb-9173-794952e53cc0.png">
?

**Comment by Lakhankumawat** [comment]
I wasn't using latest version , but hold on when i tried to use latest version still there was error that the ` package update is not out yet` like that i am sorry but I can't remember it exactly , so i used older version . After some suggestions from stackoverflow , sorry to bother 🙂
