### ISSUE TITLE
Migrate to null safety please

### ISSUE THREAD

**Issue by Toxicann** [java-james/loading_overlay#14]
Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:loading_overlay

**Comment by alejandro-rios** [comment]
@Toxicann it looks like version `0.3.0`has support for null safety, README is not updated

![Screen Shot 2022-10-13 at 16 09 25](https://user-images.githubusercontent.com/10689052/195711158-caec5f7f-f9ed-4235-b07d-728c3689246d.png)

**Comment by java-james** [comment]
Yes 0.3.0 aimed to migrate to null safety. Please let me know if this is still an issue. Closing.
