### ISSUE TITLE
Remove references to deprecated v1 Android embedding 

### ISSUE THREAD

**Issue by reidbaker** [java-james/loading_overlay#17]
Remove references to deprecated v1 Android embedding 

To ensure this plugin will work with users running the next stable version of Flutter remove references to the v1 embedding.

The v1 embedding was deprecated around 6 and a half years ago. In Flutter 3.22, the Flutter tool dropped support for building v1 apps entirely. Flutter plans to delete version one of it's Android embedding in the next stable release, per https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3 (in the "Removal of v1 Android embedding" section). 

When that deletion happens, any apps using plugins that still have references to the removed classes will fail to build when updating to the next stable version (probably Flutter `3.26`). 

As a part of this deprecation, the Flutter Android team is doing community outreach by filing bugs and submitting some pull requests to update plugins to minimize the impact this removal has on the community. 

#### Some example PRs:
- Flutter team maintained plugins: https://github.com/flutter/packages/pull/6494
- `android_alarm_manager_plus` https://github.com/fluttercommunity/plus_plugins/pull/2864 

#### Consequences:
- This change should have no impact on users of this plugin that are building apps using the v2 embedding (we don't have a percentage to share, but this is the vast majority of users). 
- It will remove support for users that are still using the v1 embedding on versions of Flutter older than `3.22`.

If this change doesn't land, this plugin will instead be broken for all apps building on the next stable version of Flutter and beyond.

#### Is there a way to support both v1 and v2 embedding apps in the next stable version of Flutter?
No.

This is the PR where we are removing the deprecated engine classes: https://github.com/flutter/engine/pull/52022

**Comment by java-james** [comment]
Thanks for the detailed issue.

I'll do some maintenance on this lib in the coming weeks

**Comment by java-james** [comment]
I believe this should not be an issue for the latest release of this library. Please feel free to re open the issue if I am wrong.

**Comment by reidbaker** [comment]
I still see [references in your example app](https://github.com/search?q=repo%3Ajava-james%2Floading_overlay%20repo%3Ajava-james%2Floading_overlay%20(%22io.flutter.view.FlutterMain%22%20OR%20%22io.flutter.view.FlutterNativeView%22%20OR%20%22io.flutter.view.FlutterView%22%20OR%20%22io.flutter.embedding.engine.plugins.shim%22%20OR%20%22io.flutter.app%22%20OR%20%22PluginRegistry.Registrar%22)%20&type=code). 
That wont impact your users but will cause the example to break.

**Comment by java-james** [comment]
Ah interesting this is a brand new example application

**Comment by reidbaker** [comment]
As in you made the example with a recent version of flutter? If so what version? I thought we had migrated all the templates but if not then I need to follow up with a flutter framework change.

**Comment by reidbaker** [comment]
From what I can tell our template code is migrated. 
https://github.com/search?q=repo%3Aflutter%2Fflutter+path%3A%2F%5Epackages%5C%2Fflutter_tools%5C%2Ftemplates%5C%2F%2F+%28%22io.flutter.view.FlutterMain%22+OR+%22io.flutter.view.FlutterNativeView%22+OR+%22io.flutter.view.FlutterView%22+OR+%22io.flutter.embedding.engine.plugins.shim%22+OR+%22io.flutter.app%22+OR+%22PluginRegistry.Registrar%22%29&type=code 

The lone example shown there happens to use the same package but does not reference any of the removed classes. 
That said if I missed something please let me know.
